"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['PhotoOrganizer.py']
APP_NAME = 'Photo Organizer'

DATA_FILES = []
OPTIONS = {'plist': {
                    'CFBundleName': APP_NAME,
                    'CFBundleDisplayName': APP_NAME,
                    'CFBundleGetInfoString': "Organize Photos",
                    'CFBundleIdentifier': "com.willduke.osx.organizer",
                    'CFBundleVersion': "0.1.0",
                    'CFBundleShortVersionString': "0.1.0",
                    'NSHumanReadableCopyright': u"Copyright © 2020, Will Duke, All Rights Reserved"},
            'iconfile': '/Users/Will/Py_Files/Photo_Organizer/camera_icon.icns'
           }
setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app']
)

# 'plist': {
#                'PyRuntimeLocations': [
#                 '@executable_path/../Frameworks/libpython3.7m.dylib',
#                 '/Users/Will/anaconda3/envs/PhotoEnv/lib/libpython3.7m.dylib'
#                ]},